import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 0,
    backgroundColor: '#F5F7FA',
  },
  topRectangle: {
    height: 10,
    backgroundColor: '#0038A8',
    width: '150%',
    marginTop: 0,
    position: 'absolute',
    top: 0,
  },
  additionalRectangle: {
    height: 10,
    backgroundColor: '#0038A8',
    width: '150%',
    marginTop: 100,
  },
  headerContainer: {
    alignItems: 'center',
    marginBottom: 16,
    marginTop: -50,
  },
  headerText: {
    fontSize: 24,
    marginBottom: 12,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  pickersContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    padding: 12,
    marginTop: 12,
  },
  pickerContainer: {
    flex: 1,
    borderColor: '#0038A8',
    borderWidth: 1.5,
    borderRadius: 12,
    marginRight: 8,
    paddingVertical: 12,
    backgroundColor: '#FAFBFC',
  },
  materialContainer: {
    marginBottom: 16,
    padding: 12,
    marginTop: 12,
  },
  material: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  weightInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
  },
  weightInput: {
    width: 80,
    textAlign: 'center',
    borderColor: '#E5E7EB',
    borderWidth: 1.5,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    fontSize: 16,
    color: '#1A1A1A',
  },
  kgText: {
    marginLeft: 12,
    fontSize: 16,
    color: '#6B7280',
    fontWeight: '500',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
    marginBottom: 90,
    gap: 12,
  },
  submitButton: {
    alignItems: 'center',
    backgroundColor: '#10B981',
    padding: 14,
    width: '48%',
    borderRadius: 12,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: '#6B7280',
    padding: 14,
    width: '48%',
    borderRadius: 12,
    shadowColor: '#6B7280',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  commentInput: {
    height: 110,
    borderColor: '#E5E7EB',
    borderWidth: 1.5,
    padding: 14,
    marginBottom: 16,
    marginLeft: 12,
    marginRight: 12,
    marginTop: 12,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    fontSize: 16,
    color: '#1A1A1A',
    textAlignVertical: 'top',
  },
  logo: {
    height: 50,
    resizeMode: 'contain',
    marginBottom: 20,
    position: 'absolute',
    top: 10,
    left: 10,
  },
  materialContent: {
    paddingBottom: 24,
  },
  name: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1A1A1A',
    marginBottom: 8,
    paddingHorizontal: 12,
  },
  colorRectangle: {
    width: 24,
    height: 24,
    borderRadius: 6,
    marginRight: 12,
  },
  weightContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  weightText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1A1A1A',
    marginRight: 12,
    minWidth: 60,
  },
  editButton: {
    backgroundColor: '#0038A8',
    width: 36,
    height: 36,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  editButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
});

export default styles;

